iscripts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scripto.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scripto/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('script1/', views.script1, name='script1'),
    path('script2/', views.script2, name='script2'),
    path('script3/', views.script3, name='script3'),
    path('script4/', views.script4, name='script4'),
    path('script5/', views.script5, name='script5'),
    path('script6/', views.nameSplit, name='script6'),
    path('script7/', views.script7, name='script7'),
    path('script7Part2/', views.script7Part2, name='script7Part2'),
    # path('script8/', views.script8, name='script8'),
    path('ds6/', views.namesplit_download, name='ds6'),
    path('ds71/', views.ds71, name='ds71'),
    path('ds72/', views.ds72, name='ds72'),

]

scripto/models.py
from django.db import models

# Create your models here.

scripto/forms.py
from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField()

class ClientForm(forms.Form):
    ch = (
        ('01','SPACE'),
        ('02','TAB'),
        ('03','CAPITAL'),
        ('04','UNDER SCORE'),
        ('05','HYPHEN'),
    )

    split_ch = (
        (False, 'No'),
        (True, 'Yes')
    )

    file_url = forms.CharField()
    start_str = forms.CharField()
    end_str = forms.CharField()
    deliminator = forms.ChoiceField(choices=ch)
    input_column_name = forms.CharField()
    output_column_name = forms.CharField()
    common_data = forms.CharField()
    split_checkbox = forms.ChoiceField(choices=split_ch)


# class SampleForm(forms.Form):
#     ch = (
#         ('01','SPACE'),
#         ('02','TAB'),
#         ('03','CAPITAL'),
#         ('04','UNDER SCORE'),
#         ('05','HYPHEN'),
#     )
#
#     split_ch = (
#         (False, 'False'),
#         (True, 'True')
#     )
#
#     file_url = forms.CharField()
#     start_str = forms.CharField()
#     end_str = forms.CharField()
#     deliminator = forms.ChoiceField(choices=ch)
#     input_column_name = forms.CharField()
#     output_column_name = forms.CharField()
#     common_data = forms.CharField()
#     split_checkbox = forms.ChoiceField(choices=split_ch)

scripto/views.py
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render
from django.conf import settings
from .forms import UploadFileForm, ClientForm
from django.core.files.storage import FileSystemStorage
import pandas as pd
import xlrd
import os
import glob
from xlwt import Workbook
from xlsxwriter import Workbook
from zipfile import ZipFile
import shutil
from urllib.parse import urlparse, parse_qs
import re
from collections import Counter


def home(request):
    return render(request, 'home.html')

# script 1 - Piwik Analytics / App Preview / ReportingScript1
def script1(request):
    try:
        if request.method == 'POST':
            form = UploadFileForm(request.POST, request.FILES)
            if form.is_valid():
                input_file = request.FILES['file']
                fs = FileSystemStorage()
                filename = fs.save(input_file.name, input_file)
                uploaded_file_url = fs.path(filename)
                # Code to read data from input excel file
                loc = uploaded_file_url

                df = pd.read_excel(loc)
                all_columns = list(df.columns)
                remap = ['visitType', 'visitIp', 'pagesCount', 'serverDatePretty', 'serverTimePretty',
                         'visitDurationPretty']
                all_pageTitle = [_a for _a in all_columns if 'pageTitle (actionDetails' in _a]
                remap += all_pageTitle

                visitType = []
                visitTyped = {}
                for i in df['visitIp'][::-1]:
                    if i not in visitTyped.keys():
                        visitTyped[i] = 1
                        visitType.append('Unique')
                    else:
                        visitType.append('Return')
                df['visitType'] = visitType[::-1]

                pagesCount = []
                for _r in range(df.shape[0]):
                    count = 0
                    for _j in all_pageTitle:
                        if pd.isna(df[_j][_r]) == False:
                            count += 1
                    pagesCount.append(count)
                df['pagesCount'] = pagesCount

                df.to_excel('output/script1/output.xlsx', index=False, columns=remap)

                fs.delete(filename)
                dout = os.path.join(os.path.dirname(__file__), "../output/script1/output.xlsx")
                down = download(request, dout)
                return down
            return render(request, 'scripto/fail.html')
        else:
            form = UploadFileForm()
        return render(request, 'scripto/upload/uploadFile.html', {'form': form})
    except:
        raise Http404

def script2(request):
    try:
        if request.method == 'POST':
            form = UploadFileForm(request.POST, request.FILES)
            if form.is_valid():
                input_file = request.FILES['file']
                fs = FileSystemStorage()
                filename = fs.save(input_file.name, input_file)
                uploaded_file_url = fs.path(filename)
                loc = uploaded_file_url

                df = pd.read_excel(loc, index_col=None)
                a = list(df.columns)

                visitType = []
                visitTyped = {}
                for i in df['visitIp']:
                    if i not in visitTyped.keys():
                        visitTyped[i] = 1
                        visitType.append('Unique')
                    else:
                        visitType.append('Return')
                df['visitType'] = visitType

                all_urls = [_a for _a in a if 'url (actionDetails' in _a]

                pagesCount = []
                vcf = []
                for _r in range(df.shape[0]):
                    c = 0
                    count = 0
                    for _j in all_urls:
                        if type(df[_j][_r]) != float and '.vcf' in df[_j][_r]:
                            c = 1
                        if type(df[_j][_r]) != float:
                            count += 1
                    if c == 0:
                        vcf.append('No')
                    else:
                        vcf.append('Yes')
                    pagesCount.append(count)
                df['pagesCount'] = pagesCount
                df['vcf downloaded'] = vcf

                remap = ['visitType', 'visitIp', 'pagesCount', 'serverDatePretty', 'serverTimePretty',
                         'visitDurationPretty', 'vcf downloaded']
                remap += all_urls
                df.to_excel('output/script2/output.xlsx', index=False, columns=remap)

                fs.delete(filename)
                dout = os.path.join(os.path.dirname(__file__), "../output/script2/output.xlsx")
                down = download(request, dout)
                return down
        else:
            form = UploadFileForm()
        return render(request, 'scripto/upload/uploadFile.html', {'form': form})
    except:
        raise Http404

# Script 3 - FIITJEE Demo / Norah Analytics / Notifications Demo / XlsxToJson
def script3(request):
    try:
        if request.method == 'POST':
            form = UploadFileForm(request.POST, request.FILES)
            if form.is_valid():
                input_file = request.FILES['file']
                fs = FileSystemStorage()
                filename = fs.save(input_file.name, input_file)
                uploaded_file_url = fs.path(filename)
                loc = uploaded_file_url
                # To open Workbook
                wb = xlrd.open_workbook(loc)
                sheet = wb.sheet_by_index(0)
                # Extracting number of rows and columns
                rows = sheet.nrows
                columns = sheet.ncols

                input_format = []
                for i in range(sheet.ncols):
                    input_format.append(sheet.cell_value(0, i))

                dic = {}
                for i in range(1,rows):
                    z = sheet.row_values(i)
                    if z[0] not in dic.keys():
                        dic[z[0]] = { "notification":[{"text":"", "title":"", "data":[]}]}
                        if dic[z[0]]["notification"][-1]["text"] != z[2]:
                            dic[z[0]]["notification"][-1]["text"] = z[2]
                            dic[z[0]]["notification"][-1]["title"] = z[1]
                            dic[z[0]]["notification"][-1]["data"].append({"id":z[4], "text":z[3]})
                        elif dic[z[0]]["notification"][-1]["text"] == z[2]:
                            dic[z[0]]["notification"][-1]["data"].append({"id":z[4], "text":z[3]})
                    else:
                        if dic[z[0]]["notification"][-1]["text"] != z[2]:
                            dic[z[0]]["notification"].append({"text":z[2], "title":z[1], "data":[{"id":z[4], "text":z[3]}]})
                        elif dic[z[0]]["notification"][-1]["text"] == z[2]:
                            dic[z[0]]["notification"][-1]["data"].append({"id":z[4], "text":z[3]})
                finaldata = {"profiles":dic}
                """
                writing data to json or text file
                """
                import json
                # Serialize the list of dicts to JSON
                j = json.dumps(finaldata, indent=4)
                # Write to file
                with open('output/script3/output.json', 'w') as f:
                    f.write(j)

                fs.delete(filename)
                dout = os.path.join(os.path.dirname(__file__), "../output/script3/output.json")
                down = download(request, dout)
                return down
            return render(request, 'scripto/fail.html')
        else:
            form = UploadFileForm()
        return render(request, 'scripto/upload/uploadFile.html', {'form': form})
    except:
        raise Http404
# Script 4 - FIITJEE Demo / Norah Analytics / Reporting Dashboard / XlsxToJson
def script4(request):
    try:
        if request.method == 'POST':
            form = UploadFileForm(request.POST, request.FILES)
            if form.is_valid():
                input_file = request.FILES['file']
                fs = FileSystemStorage()
                filename = fs.save(input_file.name, input_file)
                uploaded_file_url = fs.path(filename)
                print(input_file.name)

                zip_ref = ZipFile(uploaded_file_url, 'r')
                zip_ref.extractall(os.path.join(os.path.dirname(__file__),"../output/script4"))
                zip_ref.close()
                fs.delete(filename)

                for filename in glob.iglob(os.path.join(os.path.dirname(__file__),"../output/script4/*/**/*.xlsx"), recursive=True):
                    loc = ("%s" % filename)
                    wb = xlrd.open_workbook(loc)
                    sheet = wb.sheet_by_index(0)

                    rows = sheet.nrows
                    columns = sheet.ncols

                    input_format = []
                    input_format2 = []
                    for i in range(sheet.ncols):
                        input_format.append(sheet.cell_value(0, i))
                        input_format2.append(sheet.cell_value(1, i))

                    dic = {}
                    if input_format[0] == input_format2[0]:
                        for i in range(1, rows):
                            z = sheet.row_values(i)
                            dic2 = {}
                            for j in range(1, columns):
                                dic2[input_format[j]] = z[j]
                            if z[0] not in dic.keys():
                                dic[z[0]] = [dic2]
                            else:
                                dic[z[0]].append(dic2)
                    else:
                        for i in range(1, rows):
                            z = sheet.row_values(i)
                            for j in range(columns):
                                dic[input_format[j]] = z[j]
                    """

iscripts/scripto/templates/scripto/script7-2.html
{% extends 'base.html' %}

{% block content %}
<div class="container text-center">
    <h1>Download Files</h1><br>


    <div class="row" style="margin-bottom: 30px">
        <h3>Download Processed</h3>
        <div class="col-sm">
            <br><br>
            <button class="btn" type="submit"><a href="/ds71/">DOWNLOAD</a></button>
        </div>
    </div>


    <div class="row" style="margin-bottom: 30px">
        <h3>Download Un-Processed</h3>
        <div class="col-sm">
            <br><br>
            <button class="btn" type="submit"><a href="/ds72/">DOWNLOAD</a></button>
        </div>
    </div>
</div>
{% endblock %}

iscripts/scripto/templates/scripto/script7.html
{% extends 'base.html' %}

{% block content %}
<div class="container text-center">
    <h1>Column Names</h1><br>
    <div class="row">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                {% for a in columns %}
                    <th>{{ a }}</th>
                {% endfor %}
                </tr>
            </thead>
        </table>
    </div>

    <div class="container text-center">
        <h2>Client Input</h2><br>
    {#    <h5>"NOTE : Upload zipped folder in case of multiple files"</h5><br>#}
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4">
{#                <form method="POST" action="/script7Part2/">#}
{#                    {% csrf_token %}#}
{#                    {{ form2.as_p }}#}
{#                    {{ form.as_p }}#}
{#                    <input class="form-control" type="text" name="file_url" placeholder="file url" value="{{ file_url }}" id="file_url">#}
{#                    <input class="form-control" type="text" name="input_column_name" placeholder="Input column name" id="input_column_name">#}
{#                    <input class="form-control" type="text" name="output_column_name" placeholder="Output column name" id="output_column_name">#}
{#                    <input class="form-control" type="text" name="common_data" placeholder="Common data" id="common_data">#}
{#                    <input class="form-control" type="text" name="split_checkbox" placeholder="Split checkbox" id="split_checkbox">#}
{#                    <input class="form-control" type="text" name="start_str" placeholder="Start String" id="start_str">#}
{#                    <input class="form-control" type="text" name="end_str" placeholder="End string" id="end_str">#}
{#                    <input class="form-control" type="text" name="deliminator" placeholder="Seperator" id="deliminator">#}
{##}
{#                    <button type="submit" class="btn btn-primary">Submit</button>#}
{#                    <div class="form-group">#}
{#                        <input class="form-control-file border" type="file" name="file" required id="id_file">#}
{#                    </div>#}
{#                    <button type="submit" class="btn btn-primary">Submit</button>#}
{#                </form>#}

                <form method="POST" action="/script7Part2/">
                    {% csrf_token %}
{#                    <input type="hidden" name="csrfmiddlewaretoken" value="1QOgqNCsL9Nd1UAMF92QZtF8fYjg39KILW7OvEfgvdVGAYIRZOhGZAairXXgs0rX">#}
                    <p>
                        <label for="id_file_url">File url:</label>
                        <input type="text" name="file_url" required id="id_file_url" value="{{ file_url }}">
                    </p>
                    <p><label for="id_start_str">Start str:</label> <input type="text" name="start_str" required id="id_start_str"></p>
                    <p><label for="id_end_str">End str:</label> <input type="text" name="end_str" required id="id_end_str"></p>
                    <p>
                        <label for="id_deliminator">Deliminator:</label>
                        <select name="deliminator" id="id_deliminator">
                            <option value="01">SPACE</option>
                            <option value="02">TAB</option>
                            <option value="03">CAPITAL</option>
                            <option value="04">UNDER SCORE</option>
                            <option value="05">HYPHEN</option>
                        </select>
                    </p>
                    <p><label for="id_input_column_name">Input column name:</label> <input type="text" name="input_column_name" required id="id_input_column_name"></p>
                    <p><label for="id_output_column_name">Output column name:</label> <input type="text" name="output_column_name" required id="id_output_column_name"></p>
                    <p><label for="id_common_data">Common data:</label> <input type="text" name="common_data" required id="id_common_data"></p>

                    <p>
                        <label for="id_split_checkbox">Split checkbox:</label>
                        <select name="split_checkbox" id="id_split_checkbox">
                            <option value="False">No</option>
                            <option value="True">Yes</option>
                        </select>
                    </p>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>


            </div>
            <div class="col-sm-4"></div>
        </div>
    </div>

{#    <div class="row" style="margin-bottom: 30px">#}
{#        <div class="col-sm">#}
{#            <br><br>#}
{#            <button class="btn" type="submit"><a href="/ds6/">DOWNLOAD</a></button>#}
{#        </div>#}
{#    </div>#}
</div>
{% endblock %}